### ISSUE TITLE
Validation Message Not In `analytics.mil`

### ISSUE THREAD

**Issue by kinghchan** [FL33TW00D/deCoreML#2]
This is a very useful tool, thank you for sharing it!

It looks like the validation message is not present in the `analytics.mil` file for a profile I just ran

I profiled the `AudioEncoder.mlmodelc` from this repo: https://huggingface.co/argmaxinc/whisperkit-coreml/tree/main/openai_whisper-tiny.

For context, I have pasted the `analytics.mil` file here.

Do you have any idea why the validation message is not present? A lot of layers are running on the GPU instead of the ANE, and I wanted to know why that's the case.

I am using a MacBook Pro 15 M1 Max.
My MacOS version 14.4.1.
My Xcode is version 15.4.
I set the minimum deployment target of the CoreML file (during `coremltools` conversion) to MacOS 14.

Thank you!

[analytics.mil.txt](https://github.com/user-attachments/files/16008705/analytics.mil.txt)

**Comment by FL33TW00D** [comment]
> This is a very useful tool, thank you for sharing it!
> 
> It looks like the validation message is not present in the `analytics.mil` file for a profile I just ran
> 
> I profiled the `AudioEncoder.mlmodelc` from this repo: https://huggingface.co/argmaxinc/whisperkit-coreml/tree/main/openai_whisper-tiny.
> 
> For context, I have pasted the `analytics.mil` file here.
> 
> Do you have any idea why the validation message is not present? A lot of layers are running on the GPU instead of the ANE, and I wanted to know why that's the case.
> 
> I am using a MacBook Pro 15 M1 Max. My MacOS version 14.4.1. My Xcode is version 15.4. I set the minimum deployment target of the CoreML file (during `coremltools` conversion) to MacOS 14.
> 
> Thank you!
> 
> [analytics.mil.txt](https://github.com/user-attachments/files/16008705/analytics.mil.txt)

Hi @kinghchan,
I think in this case there is no error, it runs on the GPU because that is optimal (look at the estimated runtimes).
The fact it is `whisper-tiny` would also provide evidence for this.

Try it with a larger whisper version and see if the results are the same.

**Comment by kinghchan** [comment]
Thanks a lot @FL33TW00D for your help!

Yep gonna try the large one now, but that takes ages to run... we'll see!
